// hellosiena.com/invite?code=ABC123
//
// Landing page for a partner invite shared from the Siena mobile app. One URL
// that works from any device: phones get sent to the right store, desktops get
// told to open it on their phone (or continue signing up in the browser).
//
// Deliberately does NOT auto-redirect. The stores drop query params during
// install, so the recipient has to type the code into the app afterwards —
// which means they have to SEE it first. Auto-bouncing to the App Store would
// hide the one piece of information that makes the invite work.
//
// No data is collected here. The code is validated only when it is actually
// used, in the app or in the web signup form.

import { useEffect, useMemo, useState } from 'react';
import { useSearchParams, Link } from 'react-router-dom';

const APP_STORE_URL = 'https://apps.apple.com/app/id6786386711';
const PLAY_STORE_URL =
  'https://play.google.com/store/apps/details?id=com.siena.wellness';

type Platform = 'ios' | 'android' | 'desktop';

function detectPlatform(): Platform {
  if (typeof navigator === 'undefined') return 'desktop';
  const ua = navigator.userAgent || '';
  if (/android/i.test(ua)) return 'android';
  // iPadOS 13+ reports as Macintosh, so check for touch support as well.
  const iOSLike =
    /iPad|iPhone|iPod/.test(ua) ||
    (/Macintosh/.test(ua) && typeof document !== 'undefined' && 'ontouchend' in document);
  if (iOSLike) return 'ios';
  return 'desktop';
}

export default function InvitePage() {
  const [searchParams] = useSearchParams();
  const [copied, setCopied] = useState(false);

  // Accept both spellings: the mobile app sends ?code=, older web invite links
  // generated by SettingsPage use ?code= too, but ?invite= has been in use as
  // well and costs nothing to keep working.
  const code = (searchParams.get('code') || searchParams.get('invite') || '')
    .trim()
    .toUpperCase();

  const platform = useMemo(detectPlatform, []);

  // Stash the code so that if this person signs up in the browser, UserContext
  // can link them to the inviter. That lookup already existed and reads exactly
  // this key, but nothing was ever writing it.
  useEffect(() => {
    if (!code) return;
    try {
      localStorage.setItem('invite_code', code);
    } catch {
      /* private browsing — the code is still shown on screen */
    }
  }, [code]);

  const copyCode = async () => {
    if (!code) return;
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* clipboard unavailable — the code is visible and selectable */
    }
  };

  const storeUrl = platform === 'android' ? PLAY_STORE_URL : APP_STORE_URL;
  const storeLabel =
    platform === 'android' ? 'Get Siena on Google Play' : 'Get Siena on the App Store';

  return (
    <div className="min-h-screen bg-white flex flex-col items-center justify-center px-6 py-16">
      <div className="w-full max-w-md">
        <div className="text-center mb-10">
          <h1 className="text-3xl font-bold text-brand-blue mb-3">
            You've been invited to Siena
          </h1>
          <p className="text-gray-600 leading-relaxed">
            Siena is a wellness and relationship app for individuals and couples,
            built by licensed therapists. Someone would like to connect with you
            as their partner.
          </p>
        </div>

        {code ? (
          <div className="mb-10">
            <p className="text-xs font-semibold text-gray-500 tracking-wide uppercase text-center mb-3">
              Your invite code
            </p>
            <div className="border-2 border-brand-green rounded-2xl p-6 text-center bg-brand-green/5">
              <p className="text-4xl font-bold tracking-[0.2em] text-brand-blue font-mono break-all">
                {code}
              </p>
            </div>
            <button
              onClick={copyCode}
              className="mt-3 w-full py-3 rounded-xl border border-gray-300 text-brand-blue font-semibold hover:bg-gray-50 transition-colors"
            >
              {copied ? 'Copied' : 'Copy code'}
            </button>
            <p className="mt-4 text-sm text-gray-600 text-center leading-relaxed">
              Write this down or copy it now. After you install Siena and create
              your account, enter it in <strong>Profile &rarr; Connect with your
              partner</strong>.
            </p>
          </div>
        ) : (
          <div className="mb-10 border border-amber-300 bg-amber-50 rounded-xl p-4">
            <p className="text-sm text-amber-900 leading-relaxed">
              This link is missing its invite code. Ask your partner to send the
              invite again from the Siena app, or enter their code manually in
              Profile once you have installed it.
            </p>
          </div>
        )}

        {platform === 'desktop' ? (
          <div className="text-center">
            <div className="border border-gray-200 rounded-xl p-5 bg-gray-50 mb-5">
              <p className="text-brand-blue font-semibold mb-1">
                Open this link on your phone
              </p>
              <p className="text-sm text-gray-600 leading-relaxed">
                Siena is a mobile app. Open this page on your iPhone or Android
                device to install it.
              </p>
            </div>
            <div className="flex flex-col gap-2 text-sm">
              <a
                href={APP_STORE_URL}
                className="text-brand-green font-semibold hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                View on the App Store
              </a>
              <a
                href={PLAY_STORE_URL}
                className="text-brand-green font-semibold hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                View on Google Play
              </a>
            </div>
            <p className="mt-6 text-sm text-gray-500">
              Prefer your browser?{' '}
              <Link
                to={`/invite/signup${code ? `?code=${encodeURIComponent(code)}` : ''}`}
                className="text-brand-green font-semibold hover:underline"
              >
                Continue signing up here
              </Link>
              .
            </p>
          </div>
        ) : (
          <a
            href={storeUrl}
            className="block w-full text-center py-4 rounded-xl bg-brand-green text-white font-bold text-lg hover:opacity-90 transition-opacity"
          >
            {storeLabel}
          </a>
        )}

        <p className="mt-10 text-xs text-gray-400 text-center leading-relaxed">
          Siena is a self-guided wellness tool and is not a substitute for
          therapy or medical care.{' '}
          <Link to="/privacy" className="underline hover:text-gray-600">
            Privacy Policy
          </Link>
        </p>
      </div>
    </div>
  );
}
